// This is automatically generated by CodeBind. Please do not modify it.

public partial class UIWindow : CodeBind.ICSCodeBind
{
    public CodeBind.CSCodeBindMono Mono { get; private set; }
    public UnityEngine.Transform Transform { get; private set; }

    public UnityEngine.UI.Button ShowButton { get; private set; }


    public void InitBind(CodeBind.CSCodeBindMono mono)
    {
        Mono = mono;
        Transform = mono.transform;
        ShowButton = Mono.BindComponents[0] as UnityEngine.UI.Button;
    }

    public void ClearBind()
    {
        Mono = null;
        Transform = null;
        ShowButton = null;
    }
}
